name: Subscribe to updates

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - '**.md'
jobs:
  subscribe:
    if: github.event.pull_request.merged == true #&& (github.event.label.name == 'web' || github.event.label.name == 'ai' || github.event.label.name == 'security' || github.event.label.name == 'cs')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Changed Files Exporter
        id: changed-files
        uses: umani/changed-files@v4.0.0
        with:
          repo-token: ${{ github.token }}
          pattern: '^.*\.(md|markdown)$'
      - name: List all changed files
        run: |
          echo ${{ steps.changed-files.outputs.files_updated }};
          echo ${{ steps.changed-files.outputs.files_created }};
          echo ${{ steps.changed-files.outputs.files_deleted }};

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8
      
      - name: echo labels
        run: |
          echo "${{ steps.pr-labels.outputs.labels-object }}"

      - name: Post
        uses: dkershner6/post-api-call-action@v1
        with:
          url: "https://np4l5e.laf.run/pr"
          data: "{\"id\": \"${{ github.event.pull_request.number }}\", \"labels\": \"${{ steps.pr-labels.outputs.labels }}\", \"files_updated\": \"${{ steps.changed-files.outputs.files_updated }}\", \"files_created\": \"${{ steps.changed-files.outputs.files_created }}\", \"files_deleted\": \"${{ steps.changed-files.outputs.files_deleted }}\"}"
          # params: "{\"content\": \"Test Content\"}"