name: Subscribe to updates

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - '**.md'
jobs:
  subscribe:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Changed Files Exporter
        id: changed-files
        uses: umani/changed-files@v4.0.0
        with:
          repo-token: ${{ github.token }}
          pattern: '^.*\.(md|markdown)$'
      - name: List all changed files
        run: |
          echo ${{ steps.changed-files.outputs.files_updated }};
          echo ${{ steps.changed-files.outputs.files_created }};
          echo ${{ steps.changed-files.outputs.files_deleted }};

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8
      
      - name: echo labels
        run: |
          echo "${{ steps.pr-labels.outputs.labels-object }}"

      - name: Post
        uses: dkershner6/post-api-call-action@v1
        if: steps.changed-files.outputs.files_updated != '' && steps.changed-files.outputs.files_created != '' && steps.changed-files.outputs.files_deleted != '' && steps.pr-labels.outputs.labels-object != '{}' && (steps.pr-labels.outputs.labels-object.ai == true || steps.pr-labels.outputs.labels-object.web == true) && github.event.pull_request.body != ''
        with:
          url: "https://np4l5e.laf.run/pr"
          data: "{\"id\": \"${{ github.event.pull_request.number }}\", \"labels\": \"${{ steps.pr-labels.outputs.labels }}\", \"files_updated\": \"${{ steps.changed-files.outputs.files_updated }}\", \"files_created\": \"${{ steps.changed-files.outputs.files_created }}\", \"files_deleted\": \"${{ steps.changed-files.outputs.files_deleted }}\",\"body\":\"${{github.event.pull_request.body}}\",\"title\":\"${{github.event.pull_request.title}}\",\"url\":\"${{github.event.pull_request.html_url}}\"}"
          # params: "{\"content\": \"Test Content\"}"