name: Subscribe to updates

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - '**.md'
jobs:
  subscribe:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Changed Files Exporter
        id: changed-files
        uses: umani/changed-files@v4.0.0
        with:
          repo-token: ${{ github.token }}
          pattern: '^.*\.(md|markdown)$'

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8

      # - name: Post Data
      #   id: post-data
      #   env:
      #     ID: ${{ github.event.pull_request.number }}
      #     LABELS: ${{ steps.pr-labels.outputs.labels }}
      #     FILES_UPDATED: ${{ steps.changed-files.outputs.files_updated }}
      #     FILES_CREATED: ${{ steps.changed-files.outputs.files_created }}
      #     FILES_DELETED: ${{ steps.changed-files.outputs.files_deleted }}
      #     BODY: |
      #       |
      #       ${{ github.event.pull_request.body }}
      #     TITLE: ${{ github.event.pull_request.title }}
      #     URL: ${{ github.event.pull_request.html_url }}
      #   run: node .github/actions-scripts/post.js

      # - name: Console Log
      #   id: console-log
      #   run: echo ${{ steps.post-data.outputs.post_result }}
      
      - name: Create a pull request on target repository
        id: pull-request
        uses: octokit/request-action@v2.x
        with:
          route: POST https://np4l5e.laf.run/pr
          repo: ${{github.event.repository.full_name}}
          title: ${{ github.event.pull_request.title }}
          head: ${{ steps.branch.outputs.work_branch }}
          base: ${{ steps.branch.outputs.base_branch }}
          id: ${{ github.event.pull_request.number }}
          labels: ${{ steps.pr-labels.outputs.labels }}
          files_updated: ${{ steps.changed-files.outputs.files_updated }}
          files_created: ${{ steps.changed-files.outputs.files_created }}
          files_deleted: ${{ steps.changed-files.outputs.files_deleted }}
          source_url: ${{ github.event.pull_request.html_url }}
          body: |
            |
            ${{ github.event.pull_request.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Post
      #   uses: dkershner6/post-api-call-action@v1
      #   with:
      #     url: "https://np4l5e.laf.run/pr"
      #     data: "{\"id\": \"${{ github.event.pull_request.number }}\", \"labels\": \"${{ steps.pr-labels.outputs.labels }}\", \"files_updated\": \"${{ steps.changed-files.outputs.files_updated }}\", \"files_created\": \"${{ steps.changed-files.outputs.files_created }}\", \"files_deleted\": \"${{ steps.changed-files.outputs.files_deleted }}\",\"body\":\"${{github.event.pull_request.body}}\",\"title\":\"${{github.event.pull_request.title}}\",\"url\":\"${{github.event.pull_request.html_url}}\"}"