name: Subscribe to updates

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - '**.md'
jobs:
  subscribe:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: '**.md'
          json: "true"
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8
      
      - name: echo labels
        run: |
          echo "${{ steps.pr-labels.outputs.labels-object }}"

      - name: Post
        uses: dkershner6/post-api-call-action@v1
        with:
          url: "https://np4l5e.laf.run/pr"
          data: "{\"command\": \"publish\"}"
          # params: "{\"content\": \"Test Content\"}"